### ISSUE TITLE
train_rcnn failure with a runtime error

### ISSUE THREAD

**Issue by EverettWang** [sshaoshuai/PointRCNN#151]
After finishing training for the first proposal generation stage, I am trying to train the RCNN stage by:
 
python3 train_rcnn.py --cfg_file cfgs/default.yaml --batch_size 4 --train_mode rcnn --epochs 70  --ckpt_save_interval 2 --rpn_ckpt ../output/rpn/default/ckpt/checkpoint_epoch_200.pth

It starts fine until  hits this point:
....
2020-01-20 13:36:17,175   INFO  Done: filter TRAIN results: 3265 / 3712

2020-01-20 13:36:28,941   INFO  ==> Loading part model from checkpoint '../output/rpn/default/ckpt/checkpoint_epoch_200.pth'
2020-01-20 13:36:29,446   INFO  ==> Done (loaded 208/244)
2020-01-20 13:36:29,446   INFO  **********************Start training**********************
epochs:   0%|                                            | 0/70 [00:06<?, ?it/s]
Traceback (most recent call last):                                              
  File "train_rcnn.py", line 250, in <module>
    lr_scheduler_each_iter=(cfg.TRAIN.OPTIMIZER == 'adam_onecycle')
  File "/home/everett/DL/PointRCNN/tools/../tools/train_utils/train_utils.py", line 199, in train
    loss, tb_dict, disp_dict = self._train_it(batch)
  File "/home/everett/DL/PointRCNN/tools/../tools/train_utils/train_utils.py", line 134, in _train_it
    loss.backward()
  File "/home/everett/.local/lib/python3.6/site-packages/torch/tensor.py", line 195, in backward
    torch.autograd.backward(self, gradient, retain_graph, create_graph)
  File "/home/everett/.local/lib/python3.6/site-packages/torch/autograd/__init__.py", line 99, in backward
    allow_unreachable=True)  # allow_unreachable flag
RuntimeError: cuDNN error: CUDNN_STATUS_NOT_SUPPORTED. This error may appear if you passed in a non-contiguous input.

Does it run out of GPU memory? I am using a 1080 TI with 11G.  The OS is ubuntu 18.04 with numpy-1.18.1 pillow-7.0.0 six-1.14.0 torch-1.4.0 torchvision-0.5.0, cuda 10.1, nvidia-smi 430.50

Please help. Thanks in advance.

Everett

**Comment by NitreJohn** [comment]
CUDNN_STATUS_NOT_SUPPORTED. It seems like you need to check the version of your CUDNN.

**Comment by ShenYueling56** [comment]
Changing to cuda 10.0 may help.

**Comment by TARUSHREE** [comment]
@EverettWang Was this issue solved?

**Comment by irmowan** [comment]
This is due to the incompatibility of codebase and torch 1.4, mainly the continuity of the input tensor.
I use this patch to hack torch 1.4 and fix it.
```
def forward(self, input):
    return self.conv2d_forward(input.contiguous(), self.weight)
torch.nn.Conv2d.forward = forward
```
